spring:
  security:
    user:
      name: username
      password: password
  messages:
    basename: messages
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true  
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
