spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file://F:/Programacao/Java/SpringCourses/SpringMicroServices/MicroservicesSpringCloud/git-localconfig-repo
server:
  port: 8888

